server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  data:
    mongodb:
      port: 27017
      database: webflux
      username: root
      password: rootpassword
      auto-index-creation: true